# BEGIN COPYRIGHT BLOCK
# (C) 2018 Red Hat, Inc.
# All rights reserved.
# END COPYRIGHT BLOCK

services:
  - docker

env:
  - TARGET=fedora:27
  - TARGET=fedora:28
  - TARGET=fedora:29
  - TARGET=fedora:rawhide

install:
  - docker pull registry.fedoraproject.org/$TARGET
  - docker run
      --name=container
      --detach
      -i
      -v $(pwd):/root/jss
      registry.fedoraproject.org/$TARGET
  - docker exec container dnf install -y dnf-plugins-core gcc make rpm-build
  - docker exec container dnf copr -y enable ${JSS_4_5_REPO:-@pki/10.6}
  - docker exec container dnf builddep -y --spec /root/jss/jss.spec
  - docker exec container /root/jss/build.sh --with-timestamp --with-commit-id rpm

script:
  - docker exec container rpm -Uvh /root/build/jss/RPMS/*
